namespace Kuestenlogik.Surgewave.Protocol.Kafka.Requests;

// ────────────────────────────────────────────────────────────────
// ShareGroupHeartbeat (API Key 76)
// ────────────────────────────────────────────────────────────────

/// <summary>
/// Kafka ShareGroupHeartbeat request (API Key 76, v1).
/// KIP-932: Queues for Kafka — share group heartbeat.
/// </summary>
public sealed class ShareGroupHeartbeatRequest : KafkaRequest
{
    /// <summary>The group identifier.</summary>
    public required string GroupId { get; init; }

    /// <summary>The member ID generated by the consumer.</summary>
    public required string MemberId { get; init; }

    /// <summary>The current member epoch; 0 to join the group; -1 to leave the group.</summary>
    public int MemberEpoch { get; init; }

    /// <summary>The rack ID of the consumer, or null if not provided or unchanged.</summary>
    public string? RackId { get; init; }

    /// <summary>The subscribed topic names, or null if unchanged since last heartbeat.</summary>
    public List<string>? SubscribedTopicNames { get; init; }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        // v0+ is flexible
        writer.WriteInt16((short)ApiKey);
        writer.WriteInt16(ApiVersion);
        writer.WriteInt32(CorrelationId);
        writer.WriteCompactString(ClientId);
        writer.WriteVarInt(0); // Header tagged fields

        writer.WriteCompactString(GroupId);
        writer.WriteCompactString(MemberId);
        writer.WriteInt32(MemberEpoch);
        writer.WriteCompactString(RackId);

        if (SubscribedTopicNames == null)
        {
            writer.WriteVarInt(-1); // Null compact array
        }
        else
        {
            writer.WriteVarInt(SubscribedTopicNames.Count + 1);
            foreach (var topic in SubscribedTopicNames)
            {
                writer.WriteCompactString(topic);
            }
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static ShareGroupHeartbeatRequest ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId, string clientId)
    {
        var groupId = reader.ReadCompactString() ?? "";
        var memberId = reader.ReadCompactString() ?? "";
        var memberEpoch = reader.ReadInt32();
        var rackId = reader.ReadCompactString();

        List<string>? subscribedTopicNames = null;
        var topicCount = reader.ReadVarInt() - 1;
        if (topicCount >= 0)
        {
            subscribedTopicNames = new List<string>(topicCount);
            for (int i = 0; i < topicCount; i++)
            {
                subscribedTopicNames.Add(reader.ReadCompactString() ?? "");
            }
        }

        reader.SkipTaggedFields();

        return new ShareGroupHeartbeatRequest
        {
            ApiKey = ApiKey.ShareGroupHeartbeat,
            ApiVersion = apiVersion,
            CorrelationId = correlationId,
            ClientId = clientId,
            GroupId = groupId,
            MemberId = memberId,
            MemberEpoch = memberEpoch,
            RackId = rackId,
            SubscribedTopicNames = subscribedTopicNames
        };
    }
}

/// <summary>
/// Kafka ShareGroupHeartbeat response (API Key 76, v1).
/// </summary>
public sealed class ShareGroupHeartbeatResponse : KafkaResponse
{
    /// <summary>Duration in milliseconds for which the request was throttled.</summary>
    public int ThrottleTimeMs { get; init; }

    /// <summary>The top-level error code, or 0 if there was no error.</summary>
    public ErrorCode ErrorCode { get; init; }

    /// <summary>The top-level error message, or null if there was no error.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>The member ID.</summary>
    public string? MemberId { get; init; }

    /// <summary>The member epoch.</summary>
    public int MemberEpoch { get; init; }

    /// <summary>The heartbeat interval in milliseconds.</summary>
    public int HeartbeatIntervalMs { get; init; }

    /// <summary>The assignment, or null if not provided.</summary>
    public AssignmentInfo? Assignment { get; init; }

    public sealed class AssignmentInfo
    {
        /// <summary>The partitions assigned to the member.</summary>
        public required List<TopicPartitions> TopicPartitions { get; init; }
    }

    public sealed class TopicPartitions
    {
        /// <summary>The topic ID.</summary>
        public required Guid TopicId { get; init; }

        /// <summary>The partitions.</summary>
        public required List<int> Partitions { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        writer.WriteInt32(CorrelationId);
        writer.WriteVarInt(0); // Response header tagged fields

        writer.WriteInt32(ThrottleTimeMs);
        writer.WriteInt16((short)ErrorCode);
        writer.WriteCompactString(ErrorMessage);
        writer.WriteCompactString(MemberId);
        writer.WriteInt32(MemberEpoch);
        writer.WriteInt32(HeartbeatIntervalMs);

        if (Assignment == null)
        {
            writer.WriteVarInt(-1); // Null struct marker
        }
        else
        {
            writer.WriteVarInt(Assignment.TopicPartitions.Count + 1);
            foreach (var tp in Assignment.TopicPartitions)
            {
                writer.WriteUuid(tp.TopicId);
                writer.WriteVarInt(tp.Partitions.Count + 1);
                foreach (var partition in tp.Partitions)
                {
                    writer.WriteInt32(partition);
                }
                writer.WriteVarInt(0); // TopicPartitions tagged fields
            }
            writer.WriteVarInt(0); // Assignment tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static ShareGroupHeartbeatResponse ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId)
    {
        reader.SkipTaggedFields(); // Response header tagged fields

        var throttleTimeMs = reader.ReadInt32();
        var errorCode = (ErrorCode)reader.ReadInt16();
        var errorMessage = reader.ReadCompactString();
        var memberId = reader.ReadCompactString();
        var memberEpoch = reader.ReadInt32();
        var heartbeatIntervalMs = reader.ReadInt32();

        AssignmentInfo? assignment = null;
        var tpCount = reader.ReadVarInt() - 1;
        if (tpCount >= 0)
        {
            var topicPartitions = new List<TopicPartitions>(tpCount);
            for (int i = 0; i < tpCount; i++)
            {
                var topicId = reader.ReadUuid();
                var partCount = reader.ReadVarInt() - 1;
                var partitions = new List<int>(partCount);
                for (int j = 0; j < partCount; j++)
                {
                    partitions.Add(reader.ReadInt32());
                }
                reader.SkipTaggedFields();

                topicPartitions.Add(new TopicPartitions
                {
                    TopicId = topicId,
                    Partitions = partitions
                });
            }
            reader.SkipTaggedFields();
            assignment = new AssignmentInfo { TopicPartitions = topicPartitions };
        }

        reader.SkipTaggedFields();

        return new ShareGroupHeartbeatResponse
        {
            CorrelationId = correlationId,
            ApiVersion = apiVersion,
            ThrottleTimeMs = throttleTimeMs,
            ErrorCode = errorCode,
            ErrorMessage = errorMessage,
            MemberId = memberId,
            MemberEpoch = memberEpoch,
            HeartbeatIntervalMs = heartbeatIntervalMs,
            Assignment = assignment
        };
    }
}

// ────────────────────────────────────────────────────────────────
// ShareGroupDescribe (API Key 77)
// ────────────────────────────────────────────────────────────────

/// <summary>
/// Kafka ShareGroupDescribe request (API Key 77, v1).
/// KIP-932: Queues for Kafka — describe share groups.
/// </summary>
public sealed class ShareGroupDescribeRequest : KafkaRequest
{
    /// <summary>The IDs of the groups to describe.</summary>
    public required List<string> GroupIds { get; init; }

    /// <summary>Whether to include authorized operations.</summary>
    public bool IncludeAuthorizedOperations { get; init; }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        // v0+ is flexible
        writer.WriteInt16((short)ApiKey);
        writer.WriteInt16(ApiVersion);
        writer.WriteInt32(CorrelationId);
        writer.WriteCompactString(ClientId);
        writer.WriteVarInt(0); // Header tagged fields

        writer.WriteVarInt(GroupIds.Count + 1);
        foreach (var groupId in GroupIds)
        {
            writer.WriteCompactString(groupId);
        }

        writer.WriteBoolean(IncludeAuthorizedOperations);

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static ShareGroupDescribeRequest ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId, string clientId)
    {
        var groupCount = reader.ReadVarInt() - 1;
        var groupIds = new List<string>(groupCount);
        for (int i = 0; i < groupCount; i++)
        {
            groupIds.Add(reader.ReadCompactString() ?? "");
        }

        var includeAuthorizedOperations = reader.ReadBoolean();

        reader.SkipTaggedFields();

        return new ShareGroupDescribeRequest
        {
            ApiKey = ApiKey.ShareGroupDescribe,
            ApiVersion = apiVersion,
            CorrelationId = correlationId,
            ClientId = clientId,
            GroupIds = groupIds,
            IncludeAuthorizedOperations = includeAuthorizedOperations
        };
    }
}

/// <summary>
/// Kafka ShareGroupDescribe response (API Key 77, v1).
/// </summary>
public sealed class ShareGroupDescribeResponse : KafkaResponse
{
    /// <summary>Duration in milliseconds for which the request was throttled.</summary>
    public int ThrottleTimeMs { get; init; }

    /// <summary>Each described group.</summary>
    public required List<DescribedGroup> Groups { get; init; }

    public sealed class DescribedGroup
    {
        /// <summary>The describe error code, or 0 if there was no error.</summary>
        public ErrorCode ErrorCode { get; init; }

        /// <summary>The top-level error message, or null if there was no error.</summary>
        public string? ErrorMessage { get; init; }

        /// <summary>The group ID string.</summary>
        public required string GroupId { get; init; }

        /// <summary>The group state string, or the empty string.</summary>
        public required string GroupState { get; init; }

        /// <summary>The group epoch.</summary>
        public int GroupEpoch { get; init; }

        /// <summary>The assignment epoch.</summary>
        public int AssignmentEpoch { get; init; }

        /// <summary>The selected assignor.</summary>
        public required string AssignorName { get; init; }

        /// <summary>The members.</summary>
        public required List<Member> Members { get; init; }

        /// <summary>32-bit bitfield representing authorized operations.</summary>
        public int AuthorizedOperations { get; init; } = int.MinValue;
    }

    public sealed class Member
    {
        /// <summary>The member ID.</summary>
        public required string MemberId { get; init; }

        /// <summary>The member rack ID.</summary>
        public string? RackId { get; init; }

        /// <summary>The current member epoch.</summary>
        public int MemberEpoch { get; init; }

        /// <summary>The client ID.</summary>
        public required string ClientId { get; init; }

        /// <summary>The client host.</summary>
        public required string ClientHost { get; init; }

        /// <summary>The subscribed topic names.</summary>
        public required List<string> SubscribedTopicNames { get; init; }

        /// <summary>The current assignment.</summary>
        public required AssignmentInfo Assignment { get; init; }
    }

    public sealed class AssignmentInfo
    {
        /// <summary>The assigned topic-partitions to the member.</summary>
        public required List<ShareTopicPartitions> TopicPartitions { get; init; }
    }

    public sealed class ShareTopicPartitions
    {
        /// <summary>The topic ID.</summary>
        public required Guid TopicId { get; init; }

        /// <summary>The topic name.</summary>
        public required string TopicName { get; init; }

        /// <summary>The partitions.</summary>
        public required List<int> Partitions { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        writer.WriteInt32(CorrelationId);
        writer.WriteVarInt(0); // Response header tagged fields

        writer.WriteInt32(ThrottleTimeMs);

        writer.WriteVarInt(Groups.Count + 1);
        foreach (var group in Groups)
        {
            writer.WriteInt16((short)group.ErrorCode);
            writer.WriteCompactString(group.ErrorMessage);
            writer.WriteCompactString(group.GroupId);
            writer.WriteCompactString(group.GroupState);
            writer.WriteInt32(group.GroupEpoch);
            writer.WriteInt32(group.AssignmentEpoch);
            writer.WriteCompactString(group.AssignorName);

            writer.WriteVarInt(group.Members.Count + 1);
            foreach (var member in group.Members)
            {
                writer.WriteCompactString(member.MemberId);
                writer.WriteCompactString(member.RackId);
                writer.WriteInt32(member.MemberEpoch);
                writer.WriteCompactString(member.ClientId);
                writer.WriteCompactString(member.ClientHost);

                writer.WriteVarInt(member.SubscribedTopicNames.Count + 1);
                foreach (var topic in member.SubscribedTopicNames)
                {
                    writer.WriteCompactString(topic);
                }

                WriteShareAssignment(writer, member.Assignment);

                writer.WriteVarInt(0); // Member tagged fields
            }

            writer.WriteInt32(group.AuthorizedOperations);

            writer.WriteVarInt(0); // Group tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    private static void WriteShareAssignment(KafkaProtocolWriter writer, AssignmentInfo assignment)
    {
        writer.WriteVarInt(assignment.TopicPartitions.Count + 1);
        foreach (var tp in assignment.TopicPartitions)
        {
            writer.WriteUuid(tp.TopicId);
            writer.WriteCompactString(tp.TopicName);
            writer.WriteVarInt(tp.Partitions.Count + 1);
            foreach (var partition in tp.Partitions)
            {
                writer.WriteInt32(partition);
            }
            writer.WriteVarInt(0); // TopicPartitions tagged fields
        }
        writer.WriteVarInt(0); // Assignment tagged fields
    }

    public static ShareGroupDescribeResponse ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId)
    {
        reader.SkipTaggedFields(); // Response header tagged fields

        var throttleTimeMs = reader.ReadInt32();

        var groupCount = reader.ReadVarInt() - 1;
        var groups = new List<DescribedGroup>(groupCount);

        for (int i = 0; i < groupCount; i++)
        {
            var errorCode = (ErrorCode)reader.ReadInt16();
            var errorMessage = reader.ReadCompactString();
            var groupId = reader.ReadCompactString() ?? "";
            var groupState = reader.ReadCompactString() ?? "";
            var groupEpoch = reader.ReadInt32();
            var assignmentEpoch = reader.ReadInt32();
            var assignorName = reader.ReadCompactString() ?? "";

            var memberCount = reader.ReadVarInt() - 1;
            var members = new List<Member>(memberCount);

            for (int j = 0; j < memberCount; j++)
            {
                var memberId = reader.ReadCompactString() ?? "";
                var rackId = reader.ReadCompactString();
                var memberEpoch = reader.ReadInt32();
                var clientIdMember = reader.ReadCompactString() ?? "";
                var clientHost = reader.ReadCompactString() ?? "";

                var topicCount = reader.ReadVarInt() - 1;
                var subscribedTopicNames = new List<string>(topicCount);
                for (int k = 0; k < topicCount; k++)
                {
                    subscribedTopicNames.Add(reader.ReadCompactString() ?? "");
                }

                var memberAssignment = ReadShareAssignment(reader);

                reader.SkipTaggedFields();

                members.Add(new Member
                {
                    MemberId = memberId,
                    RackId = rackId,
                    MemberEpoch = memberEpoch,
                    ClientId = clientIdMember,
                    ClientHost = clientHost,
                    SubscribedTopicNames = subscribedTopicNames,
                    Assignment = memberAssignment
                });
            }

            var authorizedOperations = reader.ReadInt32();

            reader.SkipTaggedFields();

            groups.Add(new DescribedGroup
            {
                ErrorCode = errorCode,
                ErrorMessage = errorMessage,
                GroupId = groupId,
                GroupState = groupState,
                GroupEpoch = groupEpoch,
                AssignmentEpoch = assignmentEpoch,
                AssignorName = assignorName,
                Members = members,
                AuthorizedOperations = authorizedOperations
            });
        }

        reader.SkipTaggedFields();

        return new ShareGroupDescribeResponse
        {
            CorrelationId = correlationId,
            ApiVersion = apiVersion,
            ThrottleTimeMs = throttleTimeMs,
            Groups = groups
        };
    }

    private static AssignmentInfo ReadShareAssignment(KafkaProtocolReader reader)
    {
        var tpCount = reader.ReadVarInt() - 1;
        var topicPartitions = new List<ShareTopicPartitions>(tpCount);

        for (int i = 0; i < tpCount; i++)
        {
            var topicId = reader.ReadUuid();
            var topicName = reader.ReadCompactString() ?? "";
            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<int>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                partitions.Add(reader.ReadInt32());
            }
            reader.SkipTaggedFields();

            topicPartitions.Add(new ShareTopicPartitions
            {
                TopicId = topicId,
                TopicName = topicName,
                Partitions = partitions
            });
        }

        reader.SkipTaggedFields();

        return new AssignmentInfo { TopicPartitions = topicPartitions };
    }
}

// ────────────────────────────────────────────────────────────────
// ShareFetch (API Key 78)
// ────────────────────────────────────────────────────────────────

/// <summary>
/// Kafka ShareFetch request (API Key 78, v1-2).
/// KIP-932: Queues for Kafka — fetch records from share partitions.
/// </summary>
public sealed class ShareFetchRequest : KafkaRequest
{
    /// <summary>The group identifier.</summary>
    public string? GroupId { get; init; }

    /// <summary>The member ID.</summary>
    public string? MemberId { get; init; }

    /// <summary>The current share session epoch: 0 to open; -1 to close; otherwise increments.</summary>
    public int ShareSessionEpoch { get; init; }

    /// <summary>The maximum time in milliseconds to wait for the response.</summary>
    public int MaxWaitMs { get; init; }

    /// <summary>The minimum bytes to accumulate in the response.</summary>
    public int MinBytes { get; init; }

    /// <summary>The maximum bytes to fetch.</summary>
    public int MaxBytes { get; init; } = 0x7fffffff;

    /// <summary>The maximum number of records to fetch (v1+).</summary>
    public int MaxRecords { get; init; }

    /// <summary>The optimal number of records for batches (v1+).</summary>
    public int BatchSize { get; init; }

    /// <summary>The acquire mode: 0=batch-optimized, 1=record-limit (v2+).</summary>
    public sbyte ShareAcquireMode { get; init; }

    /// <summary>Whether Renew type acknowledgements present in AcknowledgementBatches (v2+).</summary>
    public bool IsRenewAck { get; init; }

    /// <summary>The topics to fetch.</summary>
    public required List<FetchTopic> Topics { get; init; }

    /// <summary>The partitions to remove from this share session.</summary>
    public required List<ForgottenTopic> ForgottenTopicsData { get; init; }

    public sealed class FetchTopic
    {
        /// <summary>The unique topic ID.</summary>
        public required Guid TopicId { get; init; }

        /// <summary>The partitions to fetch.</summary>
        public required List<FetchPartition> Partitions { get; init; }
    }

    public sealed class FetchPartition
    {
        /// <summary>The partition index.</summary>
        public int PartitionIndex { get; init; }

        /// <summary>Record batches to acknowledge.</summary>
        public required List<AcknowledgementBatch> AcknowledgementBatches { get; init; }
    }

    public sealed class AcknowledgementBatch
    {
        /// <summary>First offset of batch of records to acknowledge.</summary>
        public long FirstOffset { get; init; }

        /// <summary>Last offset (inclusive) of batch of records to acknowledge.</summary>
        public long LastOffset { get; init; }

        /// <summary>Array of acknowledge types — 0:Gap, 1:Accept, 2:Release, 3:Reject, 4:Renew.</summary>
        public required List<sbyte> AcknowledgeTypes { get; init; }
    }

    public sealed class ForgottenTopic
    {
        /// <summary>The unique topic ID.</summary>
        public required Guid TopicId { get; init; }

        /// <summary>The partition indexes to forget.</summary>
        public required List<int> Partitions { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        // v0+ is flexible
        writer.WriteInt16((short)ApiKey);
        writer.WriteInt16(ApiVersion);
        writer.WriteInt32(CorrelationId);
        writer.WriteCompactString(ClientId);
        writer.WriteVarInt(0); // Header tagged fields

        writer.WriteCompactString(GroupId);
        writer.WriteCompactString(MemberId);
        writer.WriteInt32(ShareSessionEpoch);
        writer.WriteInt32(MaxWaitMs);
        writer.WriteInt32(MinBytes);
        writer.WriteInt32(MaxBytes);

        if (ApiVersion >= 1)
        {
            writer.WriteInt32(MaxRecords);
            writer.WriteInt32(BatchSize);
        }

        if (ApiVersion >= 2)
        {
            writer.WriteInt8(ShareAcquireMode);
            writer.WriteBoolean(IsRenewAck);
        }

        writer.WriteVarInt(Topics.Count + 1);
        foreach (var topic in Topics)
        {
            writer.WriteUuid(topic.TopicId);
            writer.WriteVarInt(topic.Partitions.Count + 1);
            foreach (var partition in topic.Partitions)
            {
                writer.WriteInt32(partition.PartitionIndex);

                writer.WriteVarInt(partition.AcknowledgementBatches.Count + 1);
                foreach (var batch in partition.AcknowledgementBatches)
                {
                    writer.WriteInt64(batch.FirstOffset);
                    writer.WriteInt64(batch.LastOffset);
                    writer.WriteVarInt(batch.AcknowledgeTypes.Count + 1);
                    foreach (var ackType in batch.AcknowledgeTypes)
                    {
                        writer.WriteInt8(ackType);
                    }
                    writer.WriteVarInt(0); // AcknowledgementBatch tagged fields
                }

                writer.WriteVarInt(0); // FetchPartition tagged fields
            }
            writer.WriteVarInt(0); // FetchTopic tagged fields
        }

        writer.WriteVarInt(ForgottenTopicsData.Count + 1);
        foreach (var forgotten in ForgottenTopicsData)
        {
            writer.WriteUuid(forgotten.TopicId);
            writer.WriteVarInt(forgotten.Partitions.Count + 1);
            foreach (var partition in forgotten.Partitions)
            {
                writer.WriteInt32(partition);
            }
            writer.WriteVarInt(0); // ForgottenTopic tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static ShareFetchRequest ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId, string clientId)
    {
        var groupId = reader.ReadCompactString();
        var memberId = reader.ReadCompactString();
        var shareSessionEpoch = reader.ReadInt32();
        var maxWaitMs = reader.ReadInt32();
        var minBytes = reader.ReadInt32();
        var maxBytes = reader.ReadInt32();

        var maxRecords = 0;
        var batchSize = 0;
        if (apiVersion >= 1)
        {
            maxRecords = reader.ReadInt32();
            batchSize = reader.ReadInt32();
        }

        sbyte shareAcquireMode = 0;
        var isRenewAck = false;
        if (apiVersion >= 2)
        {
            shareAcquireMode = reader.ReadInt8();
            isRenewAck = reader.ReadBoolean();
        }

        var topicCount = reader.ReadVarInt() - 1;
        var topics = new List<FetchTopic>(topicCount);
        for (int i = 0; i < topicCount; i++)
        {
            var topicId = reader.ReadUuid();
            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<FetchPartition>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                var partitionIndex = reader.ReadInt32();

                var batchCount = reader.ReadVarInt() - 1;
                var batches = new List<AcknowledgementBatch>(batchCount);
                for (int k = 0; k < batchCount; k++)
                {
                    var firstOffset = reader.ReadInt64();
                    var lastOffset = reader.ReadInt64();
                    var ackTypeCount = reader.ReadVarInt() - 1;
                    var ackTypes = new List<sbyte>(ackTypeCount);
                    for (int l = 0; l < ackTypeCount; l++)
                    {
                        ackTypes.Add(reader.ReadInt8());
                    }
                    reader.SkipTaggedFields();

                    batches.Add(new AcknowledgementBatch
                    {
                        FirstOffset = firstOffset,
                        LastOffset = lastOffset,
                        AcknowledgeTypes = ackTypes
                    });
                }

                reader.SkipTaggedFields();

                partitions.Add(new FetchPartition
                {
                    PartitionIndex = partitionIndex,
                    AcknowledgementBatches = batches
                });
            }
            reader.SkipTaggedFields();

            topics.Add(new FetchTopic
            {
                TopicId = topicId,
                Partitions = partitions
            });
        }

        var forgottenCount = reader.ReadVarInt() - 1;
        var forgottenTopics = new List<ForgottenTopic>(forgottenCount);
        for (int i = 0; i < forgottenCount; i++)
        {
            var topicId = reader.ReadUuid();
            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<int>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                partitions.Add(reader.ReadInt32());
            }
            reader.SkipTaggedFields();

            forgottenTopics.Add(new ForgottenTopic
            {
                TopicId = topicId,
                Partitions = partitions
            });
        }

        reader.SkipTaggedFields();

        return new ShareFetchRequest
        {
            ApiKey = ApiKey.ShareFetch,
            ApiVersion = apiVersion,
            CorrelationId = correlationId,
            ClientId = clientId,
            GroupId = groupId,
            MemberId = memberId,
            ShareSessionEpoch = shareSessionEpoch,
            MaxWaitMs = maxWaitMs,
            MinBytes = minBytes,
            MaxBytes = maxBytes,
            MaxRecords = maxRecords,
            BatchSize = batchSize,
            ShareAcquireMode = shareAcquireMode,
            IsRenewAck = isRenewAck,
            Topics = topics,
            ForgottenTopicsData = forgottenTopics
        };
    }
}

/// <summary>
/// Kafka ShareFetch response (API Key 78, v1-2).
/// </summary>
public sealed class ShareFetchResponse : KafkaResponse
{
    /// <summary>Duration in milliseconds for which the request was throttled.</summary>
    public int ThrottleTimeMs { get; init; }

    /// <summary>The top-level response error code.</summary>
    public ErrorCode ErrorCode { get; init; }

    /// <summary>The top-level error message, or null if there was no error.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>The time in milliseconds for which the acquired records are locked (v1+).</summary>
    public int AcquisitionLockTimeoutMs { get; init; }

    /// <summary>The response topics.</summary>
    public required List<ShareFetchableTopicResponse> Responses { get; init; }

    /// <summary>Endpoints for all current leaders with NOT_LEADER_OR_FOLLOWER error.</summary>
    public required List<NodeEndpoint> NodeEndpoints { get; init; }

    public sealed class ShareFetchableTopicResponse
    {
        /// <summary>The unique topic ID.</summary>
        public required Guid TopicId { get; init; }

        /// <summary>The topic partitions.</summary>
        public required List<PartitionData> Partitions { get; init; }
    }

    public sealed class PartitionData
    {
        /// <summary>The partition index.</summary>
        public int PartitionIndex { get; init; }

        /// <summary>The fetch error code, or 0 if there was no fetch error.</summary>
        public ErrorCode ErrorCode { get; init; }

        /// <summary>The fetch error message, or null if there was no fetch error.</summary>
        public string? ErrorMessage { get; init; }

        /// <summary>The acknowledge error code, or 0 if there was no acknowledge error.</summary>
        public ErrorCode AcknowledgeErrorCode { get; init; }

        /// <summary>The acknowledge error message, or null if there was no acknowledge error.</summary>
        public string? AcknowledgeErrorMessage { get; init; }

        /// <summary>The current leader of the partition.</summary>
        public required LeaderIdAndEpoch CurrentLeader { get; init; }

        /// <summary>The record data (opaque bytes).</summary>
        public byte[]? Records { get; init; }

        /// <summary>The acquired records.</summary>
        public required List<AcquiredRecords> AcquiredRecords { get; init; }
    }

    public sealed class LeaderIdAndEpoch
    {
        /// <summary>The ID of the current leader or -1 if the leader is unknown.</summary>
        public int LeaderId { get; init; }

        /// <summary>The latest known leader epoch.</summary>
        public int LeaderEpoch { get; init; }
    }

    public sealed class AcquiredRecords
    {
        /// <summary>The earliest offset in this batch of acquired records.</summary>
        public long FirstOffset { get; init; }

        /// <summary>The last offset of this batch of acquired records.</summary>
        public long LastOffset { get; init; }

        /// <summary>The delivery count of this batch of acquired records.</summary>
        public short DeliveryCount { get; init; }
    }

    public sealed class NodeEndpoint
    {
        /// <summary>The ID of the associated node.</summary>
        public int NodeId { get; init; }

        /// <summary>The node's hostname.</summary>
        public required string Host { get; init; }

        /// <summary>The node's port.</summary>
        public int Port { get; init; }

        /// <summary>The rack of the node, or null if not assigned.</summary>
        public string? Rack { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        writer.WriteInt32(CorrelationId);
        writer.WriteVarInt(0); // Response header tagged fields

        writer.WriteInt32(ThrottleTimeMs);
        writer.WriteInt16((short)ErrorCode);
        writer.WriteCompactString(ErrorMessage);

        if (ApiVersion >= 1)
        {
            writer.WriteInt32(AcquisitionLockTimeoutMs);
        }

        writer.WriteVarInt(Responses.Count + 1);
        foreach (var response in Responses)
        {
            writer.WriteUuid(response.TopicId);
            writer.WriteVarInt(response.Partitions.Count + 1);
            foreach (var partition in response.Partitions)
            {
                writer.WriteInt32(partition.PartitionIndex);
                writer.WriteInt16((short)partition.ErrorCode);
                writer.WriteCompactString(partition.ErrorMessage);
                writer.WriteInt16((short)partition.AcknowledgeErrorCode);
                writer.WriteCompactString(partition.AcknowledgeErrorMessage);

                writer.WriteInt32(partition.CurrentLeader.LeaderId);
                writer.WriteInt32(partition.CurrentLeader.LeaderEpoch);
                writer.WriteVarInt(0); // LeaderIdAndEpoch tagged fields

                writer.WriteCompactBytes(partition.Records);

                writer.WriteVarInt(partition.AcquiredRecords.Count + 1);
                foreach (var acquired in partition.AcquiredRecords)
                {
                    writer.WriteInt64(acquired.FirstOffset);
                    writer.WriteInt64(acquired.LastOffset);
                    writer.WriteInt16(acquired.DeliveryCount);
                    writer.WriteVarInt(0); // AcquiredRecords tagged fields
                }

                writer.WriteVarInt(0); // PartitionData tagged fields
            }
            writer.WriteVarInt(0); // ShareFetchableTopicResponse tagged fields
        }

        writer.WriteVarInt(NodeEndpoints.Count + 1);
        foreach (var endpoint in NodeEndpoints)
        {
            writer.WriteInt32(endpoint.NodeId);
            writer.WriteCompactString(endpoint.Host);
            writer.WriteInt32(endpoint.Port);
            writer.WriteCompactString(endpoint.Rack);
            writer.WriteVarInt(0); // NodeEndpoint tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static ShareFetchResponse ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId)
    {
        reader.SkipTaggedFields(); // Response header tagged fields

        var throttleTimeMs = reader.ReadInt32();
        var errorCode = (ErrorCode)reader.ReadInt16();
        var errorMessage = reader.ReadCompactString();

        var acquisitionLockTimeoutMs = 0;
        if (apiVersion >= 1)
        {
            acquisitionLockTimeoutMs = reader.ReadInt32();
        }

        var responseCount = reader.ReadVarInt() - 1;
        var responses = new List<ShareFetchableTopicResponse>(responseCount);
        for (int i = 0; i < responseCount; i++)
        {
            var topicId = reader.ReadUuid();
            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<PartitionData>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                var partitionIndex = reader.ReadInt32();
                var partErrorCode = (ErrorCode)reader.ReadInt16();
                var partErrorMessage = reader.ReadCompactString();
                var ackErrorCode = (ErrorCode)reader.ReadInt16();
                var ackErrorMessage = reader.ReadCompactString();

                var leaderId = reader.ReadInt32();
                var leaderEpoch = reader.ReadInt32();
                reader.SkipTaggedFields(); // LeaderIdAndEpoch tagged fields

                var records = reader.ReadCompactBytes();

                var acquiredCount = reader.ReadVarInt() - 1;
                var acquiredRecords = new List<AcquiredRecords>(acquiredCount);
                for (int k = 0; k < acquiredCount; k++)
                {
                    var firstOffset = reader.ReadInt64();
                    var lastOffset = reader.ReadInt64();
                    var deliveryCount = reader.ReadInt16();
                    reader.SkipTaggedFields();

                    acquiredRecords.Add(new AcquiredRecords
                    {
                        FirstOffset = firstOffset,
                        LastOffset = lastOffset,
                        DeliveryCount = deliveryCount
                    });
                }

                reader.SkipTaggedFields();

                partitions.Add(new PartitionData
                {
                    PartitionIndex = partitionIndex,
                    ErrorCode = partErrorCode,
                    ErrorMessage = partErrorMessage,
                    AcknowledgeErrorCode = ackErrorCode,
                    AcknowledgeErrorMessage = ackErrorMessage,
                    CurrentLeader = new LeaderIdAndEpoch
                    {
                        LeaderId = leaderId,
                        LeaderEpoch = leaderEpoch
                    },
                    Records = records,
                    AcquiredRecords = acquiredRecords
                });
            }
            reader.SkipTaggedFields();

            responses.Add(new ShareFetchableTopicResponse
            {
                TopicId = topicId,
                Partitions = partitions
            });
        }

        var endpointCount = reader.ReadVarInt() - 1;
        var nodeEndpoints = new List<NodeEndpoint>(endpointCount);
        for (int i = 0; i < endpointCount; i++)
        {
            var nodeId = reader.ReadInt32();
            var host = reader.ReadCompactString() ?? "";
            var port = reader.ReadInt32();
            var rack = reader.ReadCompactString();
            reader.SkipTaggedFields();

            nodeEndpoints.Add(new NodeEndpoint
            {
                NodeId = nodeId,
                Host = host,
                Port = port,
                Rack = rack
            });
        }

        reader.SkipTaggedFields();

        return new ShareFetchResponse
        {
            CorrelationId = correlationId,
            ApiVersion = apiVersion,
            ThrottleTimeMs = throttleTimeMs,
            ErrorCode = errorCode,
            ErrorMessage = errorMessage,
            AcquisitionLockTimeoutMs = acquisitionLockTimeoutMs,
            Responses = responses,
            NodeEndpoints = nodeEndpoints
        };
    }
}

// ────────────────────────────────────────────────────────────────
// ShareAcknowledge (API Key 79)
// ────────────────────────────────────────────────────────────────

/// <summary>
/// Kafka ShareAcknowledge request (API Key 79, v1-2).
/// KIP-932: Queues for Kafka — acknowledge records in share partitions.
/// </summary>
public sealed class ShareAcknowledgeRequest : KafkaRequest
{
    /// <summary>The group identifier.</summary>
    public string? GroupId { get; init; }

    /// <summary>The member ID.</summary>
    public string? MemberId { get; init; }

    /// <summary>The current share session epoch: 0 to open; -1 to close; otherwise increments.</summary>
    public int ShareSessionEpoch { get; init; }

    /// <summary>Whether Renew type acknowledgements present in AcknowledgementBatches (v2+).</summary>
    public bool IsRenewAck { get; init; }

    /// <summary>The topics containing records to acknowledge.</summary>
    public required List<AcknowledgeTopic> Topics { get; init; }

    public sealed class AcknowledgeTopic
    {
        /// <summary>The unique topic ID.</summary>
        public required Guid TopicId { get; init; }

        /// <summary>The partitions containing records to acknowledge.</summary>
        public required List<AcknowledgePartition> Partitions { get; init; }
    }

    public sealed class AcknowledgePartition
    {
        /// <summary>The partition index.</summary>
        public int PartitionIndex { get; init; }

        /// <summary>Record batches to acknowledge.</summary>
        public required List<AcknowledgementBatch> AcknowledgementBatches { get; init; }
    }

    public sealed class AcknowledgementBatch
    {
        /// <summary>First offset of batch of records to acknowledge.</summary>
        public long FirstOffset { get; init; }

        /// <summary>Last offset (inclusive) of batch of records to acknowledge.</summary>
        public long LastOffset { get; init; }

        /// <summary>Array of acknowledge types — 0:Gap, 1:Accept, 2:Release, 3:Reject, 4:Renew.</summary>
        public required List<sbyte> AcknowledgeTypes { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        // v0+ is flexible
        writer.WriteInt16((short)ApiKey);
        writer.WriteInt16(ApiVersion);
        writer.WriteInt32(CorrelationId);
        writer.WriteCompactString(ClientId);
        writer.WriteVarInt(0); // Header tagged fields

        writer.WriteCompactString(GroupId);
        writer.WriteCompactString(MemberId);
        writer.WriteInt32(ShareSessionEpoch);

        if (ApiVersion >= 2)
        {
            writer.WriteBoolean(IsRenewAck);
        }

        writer.WriteVarInt(Topics.Count + 1);
        foreach (var topic in Topics)
        {
            writer.WriteUuid(topic.TopicId);
            writer.WriteVarInt(topic.Partitions.Count + 1);
            foreach (var partition in topic.Partitions)
            {
                writer.WriteInt32(partition.PartitionIndex);

                writer.WriteVarInt(partition.AcknowledgementBatches.Count + 1);
                foreach (var batch in partition.AcknowledgementBatches)
                {
                    writer.WriteInt64(batch.FirstOffset);
                    writer.WriteInt64(batch.LastOffset);
                    writer.WriteVarInt(batch.AcknowledgeTypes.Count + 1);
                    foreach (var ackType in batch.AcknowledgeTypes)
                    {
                        writer.WriteInt8(ackType);
                    }
                    writer.WriteVarInt(0); // AcknowledgementBatch tagged fields
                }

                writer.WriteVarInt(0); // AcknowledgePartition tagged fields
            }
            writer.WriteVarInt(0); // AcknowledgeTopic tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static ShareAcknowledgeRequest ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId, string clientId)
    {
        var groupId = reader.ReadCompactString();
        var memberId = reader.ReadCompactString();
        var shareSessionEpoch = reader.ReadInt32();

        var isRenewAck = false;
        if (apiVersion >= 2)
        {
            isRenewAck = reader.ReadBoolean();
        }

        var topicCount = reader.ReadVarInt() - 1;
        var topics = new List<AcknowledgeTopic>(topicCount);
        for (int i = 0; i < topicCount; i++)
        {
            var topicId = reader.ReadUuid();
            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<AcknowledgePartition>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                var partitionIndex = reader.ReadInt32();

                var batchCount = reader.ReadVarInt() - 1;
                var batches = new List<AcknowledgementBatch>(batchCount);
                for (int k = 0; k < batchCount; k++)
                {
                    var firstOffset = reader.ReadInt64();
                    var lastOffset = reader.ReadInt64();
                    var ackTypeCount = reader.ReadVarInt() - 1;
                    var ackTypes = new List<sbyte>(ackTypeCount);
                    for (int l = 0; l < ackTypeCount; l++)
                    {
                        ackTypes.Add(reader.ReadInt8());
                    }
                    reader.SkipTaggedFields();

                    batches.Add(new AcknowledgementBatch
                    {
                        FirstOffset = firstOffset,
                        LastOffset = lastOffset,
                        AcknowledgeTypes = ackTypes
                    });
                }

                reader.SkipTaggedFields();

                partitions.Add(new AcknowledgePartition
                {
                    PartitionIndex = partitionIndex,
                    AcknowledgementBatches = batches
                });
            }
            reader.SkipTaggedFields();

            topics.Add(new AcknowledgeTopic
            {
                TopicId = topicId,
                Partitions = partitions
            });
        }

        reader.SkipTaggedFields();

        return new ShareAcknowledgeRequest
        {
            ApiKey = ApiKey.ShareAcknowledge,
            ApiVersion = apiVersion,
            CorrelationId = correlationId,
            ClientId = clientId,
            GroupId = groupId,
            MemberId = memberId,
            ShareSessionEpoch = shareSessionEpoch,
            IsRenewAck = isRenewAck,
            Topics = topics
        };
    }
}

/// <summary>
/// Kafka ShareAcknowledge response (API Key 79, v1-2).
/// </summary>
public sealed class ShareAcknowledgeResponse : KafkaResponse
{
    /// <summary>Duration in milliseconds for which the request was throttled.</summary>
    public int ThrottleTimeMs { get; init; }

    /// <summary>The top-level response error code.</summary>
    public ErrorCode ErrorCode { get; init; }

    /// <summary>The top-level error message, or null if there was no error.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>The time in milliseconds for which the acquired records are locked (v2+).</summary>
    public int AcquisitionLockTimeoutMs { get; init; }

    /// <summary>The response topics.</summary>
    public required List<ShareAcknowledgeTopicResponse> Responses { get; init; }

    /// <summary>Endpoints for all current leaders with NOT_LEADER_OR_FOLLOWER error.</summary>
    public required List<NodeEndpoint> NodeEndpoints { get; init; }

    public sealed class ShareAcknowledgeTopicResponse
    {
        /// <summary>The unique topic ID.</summary>
        public required Guid TopicId { get; init; }

        /// <summary>The topic partitions.</summary>
        public required List<PartitionData> Partitions { get; init; }
    }

    public sealed class PartitionData
    {
        /// <summary>The partition index.</summary>
        public int PartitionIndex { get; init; }

        /// <summary>The error code, or 0 if there was no error.</summary>
        public ErrorCode ErrorCode { get; init; }

        /// <summary>The error message, or null if there was no error.</summary>
        public string? ErrorMessage { get; init; }

        /// <summary>The current leader of the partition.</summary>
        public required LeaderIdAndEpoch CurrentLeader { get; init; }
    }

    public sealed class LeaderIdAndEpoch
    {
        /// <summary>The ID of the current leader or -1 if the leader is unknown.</summary>
        public int LeaderId { get; init; }

        /// <summary>The latest known leader epoch.</summary>
        public int LeaderEpoch { get; init; }
    }

    public sealed class NodeEndpoint
    {
        /// <summary>The ID of the associated node.</summary>
        public int NodeId { get; init; }

        /// <summary>The node's hostname.</summary>
        public required string Host { get; init; }

        /// <summary>The node's port.</summary>
        public int Port { get; init; }

        /// <summary>The rack of the node, or null if not assigned.</summary>
        public string? Rack { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        writer.WriteInt32(CorrelationId);
        writer.WriteVarInt(0); // Response header tagged fields

        writer.WriteInt32(ThrottleTimeMs);
        writer.WriteInt16((short)ErrorCode);
        writer.WriteCompactString(ErrorMessage);

        if (ApiVersion >= 2)
        {
            writer.WriteInt32(AcquisitionLockTimeoutMs);
        }

        writer.WriteVarInt(Responses.Count + 1);
        foreach (var response in Responses)
        {
            writer.WriteUuid(response.TopicId);
            writer.WriteVarInt(response.Partitions.Count + 1);
            foreach (var partition in response.Partitions)
            {
                writer.WriteInt32(partition.PartitionIndex);
                writer.WriteInt16((short)partition.ErrorCode);
                writer.WriteCompactString(partition.ErrorMessage);

                writer.WriteInt32(partition.CurrentLeader.LeaderId);
                writer.WriteInt32(partition.CurrentLeader.LeaderEpoch);
                writer.WriteVarInt(0); // LeaderIdAndEpoch tagged fields

                writer.WriteVarInt(0); // PartitionData tagged fields
            }
            writer.WriteVarInt(0); // ShareAcknowledgeTopicResponse tagged fields
        }

        writer.WriteVarInt(NodeEndpoints.Count + 1);
        foreach (var endpoint in NodeEndpoints)
        {
            writer.WriteInt32(endpoint.NodeId);
            writer.WriteCompactString(endpoint.Host);
            writer.WriteInt32(endpoint.Port);
            writer.WriteCompactString(endpoint.Rack);
            writer.WriteVarInt(0); // NodeEndpoint tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static ShareAcknowledgeResponse ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId)
    {
        reader.SkipTaggedFields(); // Response header tagged fields

        var throttleTimeMs = reader.ReadInt32();
        var errorCode = (ErrorCode)reader.ReadInt16();
        var errorMessage = reader.ReadCompactString();

        var acquisitionLockTimeoutMs = 0;
        if (apiVersion >= 2)
        {
            acquisitionLockTimeoutMs = reader.ReadInt32();
        }

        var responseCount = reader.ReadVarInt() - 1;
        var responses = new List<ShareAcknowledgeTopicResponse>(responseCount);
        for (int i = 0; i < responseCount; i++)
        {
            var topicId = reader.ReadUuid();
            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<PartitionData>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                var partitionIndex = reader.ReadInt32();
                var partErrorCode = (ErrorCode)reader.ReadInt16();
                var partErrorMessage = reader.ReadCompactString();

                var leaderId = reader.ReadInt32();
                var leaderEpoch = reader.ReadInt32();
                reader.SkipTaggedFields(); // LeaderIdAndEpoch tagged fields

                reader.SkipTaggedFields();

                partitions.Add(new PartitionData
                {
                    PartitionIndex = partitionIndex,
                    ErrorCode = partErrorCode,
                    ErrorMessage = partErrorMessage,
                    CurrentLeader = new LeaderIdAndEpoch
                    {
                        LeaderId = leaderId,
                        LeaderEpoch = leaderEpoch
                    }
                });
            }
            reader.SkipTaggedFields();

            responses.Add(new ShareAcknowledgeTopicResponse
            {
                TopicId = topicId,
                Partitions = partitions
            });
        }

        var endpointCount = reader.ReadVarInt() - 1;
        var nodeEndpoints = new List<NodeEndpoint>(endpointCount);
        for (int i = 0; i < endpointCount; i++)
        {
            var nodeId = reader.ReadInt32();
            var host = reader.ReadCompactString() ?? "";
            var port = reader.ReadInt32();
            var rack = reader.ReadCompactString();
            reader.SkipTaggedFields();

            nodeEndpoints.Add(new NodeEndpoint
            {
                NodeId = nodeId,
                Host = host,
                Port = port,
                Rack = rack
            });
        }

        reader.SkipTaggedFields();

        return new ShareAcknowledgeResponse
        {
            CorrelationId = correlationId,
            ApiVersion = apiVersion,
            ThrottleTimeMs = throttleTimeMs,
            ErrorCode = errorCode,
            ErrorMessage = errorMessage,
            AcquisitionLockTimeoutMs = acquisitionLockTimeoutMs,
            Responses = responses,
            NodeEndpoints = nodeEndpoints
        };
    }
}

// ────────────────────────────────────────────────────────────────
// DescribeShareGroupOffsets (API Key 90)
// ────────────────────────────────────────────────────────────────

/// <summary>
/// Kafka DescribeShareGroupOffsets request (API Key 90, v0-1).
/// KIP-932: Queues for Kafka — describe share group offsets.
/// </summary>
public sealed class DescribeShareGroupOffsetsRequest : KafkaRequest
{
    /// <summary>The groups to describe offsets for.</summary>
    public required List<DescribeGroup> Groups { get; init; }

    public sealed class DescribeGroup
    {
        /// <summary>The group identifier.</summary>
        public required string GroupId { get; init; }

        /// <summary>The topics to describe offsets for, or null for all topic-partitions.</summary>
        public List<DescribeTopic>? Topics { get; init; }
    }

    public sealed class DescribeTopic
    {
        /// <summary>The topic name.</summary>
        public required string TopicName { get; init; }

        /// <summary>The partitions.</summary>
        public required List<int> Partitions { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        // v0+ is flexible
        writer.WriteInt16((short)ApiKey);
        writer.WriteInt16(ApiVersion);
        writer.WriteInt32(CorrelationId);
        writer.WriteCompactString(ClientId);
        writer.WriteVarInt(0); // Header tagged fields

        writer.WriteVarInt(Groups.Count + 1);
        foreach (var group in Groups)
        {
            writer.WriteCompactString(group.GroupId);

            if (group.Topics == null)
            {
                writer.WriteVarInt(-1); // Null compact array
            }
            else
            {
                writer.WriteVarInt(group.Topics.Count + 1);
                foreach (var topic in group.Topics)
                {
                    writer.WriteCompactString(topic.TopicName);
                    writer.WriteVarInt(topic.Partitions.Count + 1);
                    foreach (var partition in topic.Partitions)
                    {
                        writer.WriteInt32(partition);
                    }
                    writer.WriteVarInt(0); // DescribeTopic tagged fields
                }
            }

            writer.WriteVarInt(0); // DescribeGroup tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static DescribeShareGroupOffsetsRequest ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId, string clientId)
    {
        var groupCount = reader.ReadVarInt() - 1;
        var groups = new List<DescribeGroup>(groupCount);
        for (int i = 0; i < groupCount; i++)
        {
            var groupId = reader.ReadCompactString() ?? "";

            List<DescribeTopic>? topics = null;
            var topicCount = reader.ReadVarInt() - 1;
            if (topicCount >= 0)
            {
                topics = new List<DescribeTopic>(topicCount);
                for (int j = 0; j < topicCount; j++)
                {
                    var topicName = reader.ReadCompactString() ?? "";
                    var partCount = reader.ReadVarInt() - 1;
                    var partitions = new List<int>(partCount);
                    for (int k = 0; k < partCount; k++)
                    {
                        partitions.Add(reader.ReadInt32());
                    }
                    reader.SkipTaggedFields();

                    topics.Add(new DescribeTopic
                    {
                        TopicName = topicName,
                        Partitions = partitions
                    });
                }
            }

            reader.SkipTaggedFields();

            groups.Add(new DescribeGroup
            {
                GroupId = groupId,
                Topics = topics
            });
        }

        reader.SkipTaggedFields();

        return new DescribeShareGroupOffsetsRequest
        {
            ApiKey = ApiKey.DescribeShareGroupOffsets,
            ApiVersion = apiVersion,
            CorrelationId = correlationId,
            ClientId = clientId,
            Groups = groups
        };
    }
}

/// <summary>
/// Kafka DescribeShareGroupOffsets response (API Key 90, v0-1).
/// </summary>
public sealed class DescribeShareGroupOffsetsResponse : KafkaResponse
{
    /// <summary>Duration in milliseconds for which the request was throttled.</summary>
    public int ThrottleTimeMs { get; init; }

    /// <summary>The results for each group.</summary>
    public required List<DescribeGroupResult> Groups { get; init; }

    public sealed class DescribeGroupResult
    {
        /// <summary>The group identifier.</summary>
        public required string GroupId { get; init; }

        /// <summary>The results for each topic.</summary>
        public required List<DescribeTopicResult> Topics { get; init; }

        /// <summary>The group-level error code, or 0 if there was no error.</summary>
        public ErrorCode ErrorCode { get; init; }

        /// <summary>The group-level error message, or null if there was no error.</summary>
        public string? ErrorMessage { get; init; }
    }

    public sealed class DescribeTopicResult
    {
        /// <summary>The topic name.</summary>
        public required string TopicName { get; init; }

        /// <summary>The unique topic ID.</summary>
        public Guid TopicId { get; init; }

        /// <summary>The partition results.</summary>
        public required List<DescribePartitionResult> Partitions { get; init; }
    }

    public sealed class DescribePartitionResult
    {
        /// <summary>The partition index.</summary>
        public int PartitionIndex { get; init; }

        /// <summary>The share-partition start offset.</summary>
        public long StartOffset { get; init; }

        /// <summary>The leader epoch of the partition.</summary>
        public int LeaderEpoch { get; init; }

        /// <summary>The share-partition lag (v1+).</summary>
        public long Lag { get; init; } = -1;

        /// <summary>The partition-level error code, or 0 if there was no error.</summary>
        public ErrorCode ErrorCode { get; init; }

        /// <summary>The partition-level error message, or null if there was no error.</summary>
        public string? ErrorMessage { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        writer.WriteInt32(CorrelationId);
        writer.WriteVarInt(0); // Response header tagged fields

        writer.WriteInt32(ThrottleTimeMs);

        writer.WriteVarInt(Groups.Count + 1);
        foreach (var group in Groups)
        {
            writer.WriteCompactString(group.GroupId);

            writer.WriteVarInt(group.Topics.Count + 1);
            foreach (var topic in group.Topics)
            {
                writer.WriteCompactString(topic.TopicName);
                writer.WriteUuid(topic.TopicId);

                writer.WriteVarInt(topic.Partitions.Count + 1);
                foreach (var partition in topic.Partitions)
                {
                    writer.WriteInt32(partition.PartitionIndex);
                    writer.WriteInt64(partition.StartOffset);
                    writer.WriteInt32(partition.LeaderEpoch);

                    if (ApiVersion >= 1)
                    {
                        writer.WriteInt64(partition.Lag);
                    }

                    writer.WriteInt16((short)partition.ErrorCode);
                    writer.WriteCompactString(partition.ErrorMessage);
                    writer.WriteVarInt(0); // Partition tagged fields
                }
                writer.WriteVarInt(0); // Topic tagged fields
            }

            writer.WriteInt16((short)group.ErrorCode);
            writer.WriteCompactString(group.ErrorMessage);
            writer.WriteVarInt(0); // Group tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static DescribeShareGroupOffsetsResponse ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId)
    {
        reader.SkipTaggedFields(); // Response header tagged fields

        var throttleTimeMs = reader.ReadInt32();

        var groupCount = reader.ReadVarInt() - 1;
        var groups = new List<DescribeGroupResult>(groupCount);
        for (int i = 0; i < groupCount; i++)
        {
            var groupId = reader.ReadCompactString() ?? "";

            var topicCount = reader.ReadVarInt() - 1;
            var topics = new List<DescribeTopicResult>(topicCount);
            for (int j = 0; j < topicCount; j++)
            {
                var topicName = reader.ReadCompactString() ?? "";
                var topicId = reader.ReadUuid();

                var partCount = reader.ReadVarInt() - 1;
                var partitions = new List<DescribePartitionResult>(partCount);
                for (int k = 0; k < partCount; k++)
                {
                    var partitionIndex = reader.ReadInt32();
                    var startOffset = reader.ReadInt64();
                    var leaderEpoch = reader.ReadInt32();

                    long lag = -1;
                    if (apiVersion >= 1)
                    {
                        lag = reader.ReadInt64();
                    }

                    var errorCode = (ErrorCode)reader.ReadInt16();
                    var errorMessage = reader.ReadCompactString();
                    reader.SkipTaggedFields();

                    partitions.Add(new DescribePartitionResult
                    {
                        PartitionIndex = partitionIndex,
                        StartOffset = startOffset,
                        LeaderEpoch = leaderEpoch,
                        Lag = lag,
                        ErrorCode = errorCode,
                        ErrorMessage = errorMessage
                    });
                }
                reader.SkipTaggedFields();

                topics.Add(new DescribeTopicResult
                {
                    TopicName = topicName,
                    TopicId = topicId,
                    Partitions = partitions
                });
            }

            var groupErrorCode = (ErrorCode)reader.ReadInt16();
            var groupErrorMessage = reader.ReadCompactString();
            reader.SkipTaggedFields();

            groups.Add(new DescribeGroupResult
            {
                GroupId = groupId,
                Topics = topics,
                ErrorCode = groupErrorCode,
                ErrorMessage = groupErrorMessage
            });
        }

        reader.SkipTaggedFields();

        return new DescribeShareGroupOffsetsResponse
        {
            CorrelationId = correlationId,
            ApiVersion = apiVersion,
            ThrottleTimeMs = throttleTimeMs,
            Groups = groups
        };
    }
}

// ────────────────────────────────────────────────────────────────
// AlterShareGroupOffsets (API Key 91)
// ────────────────────────────────────────────────────────────────

/// <summary>
/// Kafka AlterShareGroupOffsets request (API Key 91, v0-0).
/// KIP-932: Queues for Kafka — alter share group offsets.
/// </summary>
public sealed class AlterShareGroupOffsetsRequest : KafkaRequest
{
    /// <summary>The group identifier.</summary>
    public required string GroupId { get; init; }

    /// <summary>The topics to alter offsets for.</summary>
    public required List<AlterTopic> Topics { get; init; }

    public sealed class AlterTopic
    {
        /// <summary>The topic name.</summary>
        public required string TopicName { get; init; }

        /// <summary>Each partition to alter offsets for.</summary>
        public required List<AlterPartition> Partitions { get; init; }
    }

    public sealed class AlterPartition
    {
        /// <summary>The partition index.</summary>
        public int PartitionIndex { get; init; }

        /// <summary>The share-partition start offset.</summary>
        public long StartOffset { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        // v0 is flexible
        writer.WriteInt16((short)ApiKey);
        writer.WriteInt16(ApiVersion);
        writer.WriteInt32(CorrelationId);
        writer.WriteCompactString(ClientId);
        writer.WriteVarInt(0); // Header tagged fields

        writer.WriteCompactString(GroupId);

        writer.WriteVarInt(Topics.Count + 1);
        foreach (var topic in Topics)
        {
            writer.WriteCompactString(topic.TopicName);
            writer.WriteVarInt(topic.Partitions.Count + 1);
            foreach (var partition in topic.Partitions)
            {
                writer.WriteInt32(partition.PartitionIndex);
                writer.WriteInt64(partition.StartOffset);
                writer.WriteVarInt(0); // Partition tagged fields
            }
            writer.WriteVarInt(0); // Topic tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static AlterShareGroupOffsetsRequest ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId, string clientId)
    {
        var groupId = reader.ReadCompactString() ?? "";

        var topicCount = reader.ReadVarInt() - 1;
        var topics = new List<AlterTopic>(topicCount);
        for (int i = 0; i < topicCount; i++)
        {
            var topicName = reader.ReadCompactString() ?? "";
            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<AlterPartition>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                var partitionIndex = reader.ReadInt32();
                var startOffset = reader.ReadInt64();
                reader.SkipTaggedFields();

                partitions.Add(new AlterPartition
                {
                    PartitionIndex = partitionIndex,
                    StartOffset = startOffset
                });
            }
            reader.SkipTaggedFields();

            topics.Add(new AlterTopic
            {
                TopicName = topicName,
                Partitions = partitions
            });
        }

        reader.SkipTaggedFields();

        return new AlterShareGroupOffsetsRequest
        {
            ApiKey = ApiKey.AlterShareGroupOffsets,
            ApiVersion = apiVersion,
            CorrelationId = correlationId,
            ClientId = clientId,
            GroupId = groupId,
            Topics = topics
        };
    }
}

/// <summary>
/// Kafka AlterShareGroupOffsets response (API Key 91, v0-0).
/// </summary>
public sealed class AlterShareGroupOffsetsResponse : KafkaResponse
{
    /// <summary>Duration in milliseconds for which the request was throttled.</summary>
    public int ThrottleTimeMs { get; init; }

    /// <summary>The top-level error code, or 0 if there was no error.</summary>
    public ErrorCode ErrorCode { get; init; }

    /// <summary>The top-level error message, or null if there was no error.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>The results for each topic.</summary>
    public required List<AlterTopicResult> Responses { get; init; }

    public sealed class AlterTopicResult
    {
        /// <summary>The topic name.</summary>
        public required string TopicName { get; init; }

        /// <summary>The unique topic ID.</summary>
        public Guid TopicId { get; init; }

        /// <summary>The partition results.</summary>
        public required List<AlterPartitionResult> Partitions { get; init; }
    }

    public sealed class AlterPartitionResult
    {
        /// <summary>The partition index.</summary>
        public int PartitionIndex { get; init; }

        /// <summary>The error code, or 0 if there was no error.</summary>
        public ErrorCode ErrorCode { get; init; }

        /// <summary>The error message, or null if there was no error.</summary>
        public string? ErrorMessage { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        writer.WriteInt32(CorrelationId);
        writer.WriteVarInt(0); // Response header tagged fields

        writer.WriteInt32(ThrottleTimeMs);
        writer.WriteInt16((short)ErrorCode);
        writer.WriteCompactString(ErrorMessage);

        writer.WriteVarInt(Responses.Count + 1);
        foreach (var response in Responses)
        {
            writer.WriteCompactString(response.TopicName);
            writer.WriteUuid(response.TopicId);

            writer.WriteVarInt(response.Partitions.Count + 1);
            foreach (var partition in response.Partitions)
            {
                writer.WriteInt32(partition.PartitionIndex);
                writer.WriteInt16((short)partition.ErrorCode);
                writer.WriteCompactString(partition.ErrorMessage);
                writer.WriteVarInt(0); // Partition tagged fields
            }
            writer.WriteVarInt(0); // Topic tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static AlterShareGroupOffsetsResponse ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId)
    {
        reader.SkipTaggedFields(); // Response header tagged fields

        var throttleTimeMs = reader.ReadInt32();
        var errorCode = (ErrorCode)reader.ReadInt16();
        var errorMessage = reader.ReadCompactString();

        var responseCount = reader.ReadVarInt() - 1;
        var responses = new List<AlterTopicResult>(responseCount);
        for (int i = 0; i < responseCount; i++)
        {
            var topicName = reader.ReadCompactString() ?? "";
            var topicId = reader.ReadUuid();

            var partCount = reader.ReadVarInt() - 1;
            var partitions = new List<AlterPartitionResult>(partCount);
            for (int j = 0; j < partCount; j++)
            {
                var partitionIndex = reader.ReadInt32();
                var partErrorCode = (ErrorCode)reader.ReadInt16();
                var partErrorMessage = reader.ReadCompactString();
                reader.SkipTaggedFields();

                partitions.Add(new AlterPartitionResult
                {
                    PartitionIndex = partitionIndex,
                    ErrorCode = partErrorCode,
                    ErrorMessage = partErrorMessage
                });
            }
            reader.SkipTaggedFields();

            responses.Add(new AlterTopicResult
            {
                TopicName = topicName,
                TopicId = topicId,
                Partitions = partitions
            });
        }

        reader.SkipTaggedFields();

        return new AlterShareGroupOffsetsResponse
        {
            CorrelationId = correlationId,
            ApiVersion = apiVersion,
            ThrottleTimeMs = throttleTimeMs,
            ErrorCode = errorCode,
            ErrorMessage = errorMessage,
            Responses = responses
        };
    }
}

// ────────────────────────────────────────────────────────────────
// DeleteShareGroupOffsets (API Key 92)
// ────────────────────────────────────────────────────────────────

/// <summary>
/// Kafka DeleteShareGroupOffsets request (API Key 92, v0-0).
/// KIP-932: Queues for Kafka — delete share group offsets.
/// </summary>
public sealed class DeleteShareGroupOffsetsRequest : KafkaRequest
{
    /// <summary>The group identifier.</summary>
    public required string GroupId { get; init; }

    /// <summary>The topics to delete offsets for.</summary>
    public required List<DeleteTopic> Topics { get; init; }

    public sealed class DeleteTopic
    {
        /// <summary>The topic name.</summary>
        public required string TopicName { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        // v0 is flexible
        writer.WriteInt16((short)ApiKey);
        writer.WriteInt16(ApiVersion);
        writer.WriteInt32(CorrelationId);
        writer.WriteCompactString(ClientId);
        writer.WriteVarInt(0); // Header tagged fields

        writer.WriteCompactString(GroupId);

        writer.WriteVarInt(Topics.Count + 1);
        foreach (var topic in Topics)
        {
            writer.WriteCompactString(topic.TopicName);
            writer.WriteVarInt(0); // Topic tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static DeleteShareGroupOffsetsRequest ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId, string clientId)
    {
        var groupId = reader.ReadCompactString() ?? "";

        var topicCount = reader.ReadVarInt() - 1;
        var topics = new List<DeleteTopic>(topicCount);
        for (int i = 0; i < topicCount; i++)
        {
            var topicName = reader.ReadCompactString() ?? "";
            reader.SkipTaggedFields();

            topics.Add(new DeleteTopic
            {
                TopicName = topicName
            });
        }

        reader.SkipTaggedFields();

        return new DeleteShareGroupOffsetsRequest
        {
            ApiKey = ApiKey.DeleteShareGroupOffsets,
            ApiVersion = apiVersion,
            CorrelationId = correlationId,
            ClientId = clientId,
            GroupId = groupId,
            Topics = topics
        };
    }
}

/// <summary>
/// Kafka DeleteShareGroupOffsets response (API Key 92, v0-0).
/// </summary>
public sealed class DeleteShareGroupOffsetsResponse : KafkaResponse
{
    /// <summary>Duration in milliseconds for which the request was throttled.</summary>
    public int ThrottleTimeMs { get; init; }

    /// <summary>The top-level error code, or 0 if there was no error.</summary>
    public ErrorCode ErrorCode { get; init; }

    /// <summary>The top-level error message, or null if there was no error.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>The results for each topic.</summary>
    public required List<DeleteTopicResult> Responses { get; init; }

    public sealed class DeleteTopicResult
    {
        /// <summary>The topic name.</summary>
        public required string TopicName { get; init; }

        /// <summary>The unique topic ID.</summary>
        public Guid TopicId { get; init; }

        /// <summary>The topic-level error code, or 0 if there was no error.</summary>
        public ErrorCode ErrorCode { get; init; }

        /// <summary>The topic-level error message, or null if there was no error.</summary>
        public string? ErrorMessage { get; init; }
    }

    public override void WriteTo(KafkaProtocolWriter writer)
    {
        writer.WriteInt32(CorrelationId);
        writer.WriteVarInt(0); // Response header tagged fields

        writer.WriteInt32(ThrottleTimeMs);
        writer.WriteInt16((short)ErrorCode);
        writer.WriteCompactString(ErrorMessage);

        writer.WriteVarInt(Responses.Count + 1);
        foreach (var response in Responses)
        {
            writer.WriteCompactString(response.TopicName);
            writer.WriteUuid(response.TopicId);
            writer.WriteInt16((short)response.ErrorCode);
            writer.WriteCompactString(response.ErrorMessage);
            writer.WriteVarInt(0); // Topic tagged fields
        }

        writer.WriteVarInt(0); // Body tagged fields
    }

    public static DeleteShareGroupOffsetsResponse ReadFrom(KafkaProtocolReader reader, short apiVersion, int correlationId)
    {
        reader.SkipTaggedFields(); // Response header tagged fields

        var throttleTimeMs = reader.ReadInt32();
        var errorCode = (ErrorCode)reader.ReadInt16();
        var errorMessage = reader.ReadCompactString();

        var responseCount = reader.ReadVarInt() - 1;
        var responses = new List<DeleteTopicResult>(responseCount);
        for (int i = 0; i < responseCount; i++)
        {
            var topicName = reader.ReadCompactString() ?? "";
            var topicId = reader.ReadUuid();
            var topicErrorCode = (ErrorCode)reader.ReadInt16();
            var topicErrorMessage = reader.ReadCompactString();
            reader.SkipTaggedFields();

            responses.Add(new DeleteTopicResult
            {
                TopicName = topicName,
                TopicId = topicId,
                ErrorCode = topicErrorCode,
                ErrorMessage = topicErrorMessage
            });
        }

        reader.SkipTaggedFields();

        return new DeleteShareGroupOffsetsResponse
        {
            CorrelationId = correlationId,
            ApiVersion = apiVersion,
            ThrottleTimeMs = throttleTimeMs,
            ErrorCode = errorCode,
            ErrorMessage = errorMessage,
            Responses = responses
        };
    }
}
