namespace Kuestenlogik.Surgewave.Broker.AutoTuning;

/// <summary>
/// Represents a configuration change recommendation generated by the auto-tuning engine.
/// </summary>
public sealed record AutoTuningRecommendation
{
    /// <summary>
    /// The unique identifier of the tuning rule that generated this recommendation.
    /// </summary>
    public required string RuleId { get; init; }

    /// <summary>
    /// A human-readable description of the recommendation.
    /// </summary>
    public required string Description { get; init; }

    /// <summary>
    /// The configuration key that should be changed.
    /// </summary>
    public required string ConfigKey { get; init; }

    /// <summary>
    /// The current value of the configuration.
    /// </summary>
    public required string CurrentValue { get; init; }

    /// <summary>
    /// The suggested new value for the configuration.
    /// </summary>
    public required string SuggestedValue { get; init; }

    /// <summary>
    /// The reason why this change is recommended.
    /// </summary>
    public required string Reason { get; init; }

    /// <summary>
    /// Whether this recommendation was automatically applied.
    /// </summary>
    public bool WasAutoApplied { get; init; }

    /// <summary>
    /// When this recommendation was generated.
    /// </summary>
    public DateTimeOffset Timestamp { get; init; }
}
