namespace Kuestenlogik.Surgewave.Control.Models.Assistant;

/// <summary>
/// A single message in an assistant conversation.
/// </summary>
public sealed class AssistantMessage
{
    /// <summary>Role of the message author: "user", "assistant", or "system".</summary>
    public required string Role { get; init; }

    /// <summary>Text content of the message.</summary>
    public required string Content { get; set; }

    /// <summary>When the message was created.</summary>
    public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.Now;

    /// <summary>SQL generated by natural-language translation, if applicable.</summary>
    public string? GeneratedSql { get; init; }

    /// <summary>Anomalies detected in the current metrics snapshot.</summary>
    public List<AnomalyDetection>? Anomalies { get; init; }

    /// <summary>Tuning recommendations produced for the current state.</summary>
    public List<TuningRecommendation>? Recommendations { get; init; }
}

/// <summary>
/// An anomaly detected in broker metrics.
/// </summary>
public sealed class AnomalyDetection
{
    /// <summary>Kind of anomaly: ThroughputDrop, LatencySpike, ErrorRate, ConsumerLag, ConnectionSaturation.</summary>
    public required string Type { get; init; }

    /// <summary>Severity level: Info, Warning, or Critical.</summary>
    public required string Severity { get; init; }

    /// <summary>Affected resource (topic name, consumer group, broker id).</summary>
    public required string Resource { get; init; }

    /// <summary>Human-readable explanation of the anomaly.</summary>
    public required string Description { get; init; }

    /// <summary>The metric value that triggered detection.</summary>
    public double CurrentValue { get; init; }

    /// <summary>The expected baseline value for comparison.</summary>
    public double BaselineValue { get; init; }

    /// <summary>Percentage deviation from the baseline.</summary>
    public double DeviationPercent { get; init; }
}

/// <summary>
/// A configuration tuning recommendation.
/// </summary>
public sealed class TuningRecommendation
{
    /// <summary>Short title describing the recommendation.</summary>
    public required string Title { get; init; }

    /// <summary>Detailed explanation and reasoning.</summary>
    public required string Description { get; init; }

    /// <summary>Configuration key to change, if applicable.</summary>
    public string? ConfigKey { get; init; }

    /// <summary>Suggested new value for the configuration key.</summary>
    public string? SuggestedValue { get; init; }

    /// <summary>Current value of the configuration key.</summary>
    public string? CurrentValue { get; init; }

    /// <summary>Expected impact: High, Medium, or Low.</summary>
    public required string Impact { get; init; }

    /// <summary>Category: Producer, Consumer, Broker, or Storage.</summary>
    public required string Category { get; init; }
}

/// <summary>
/// Configuration for the assistant feature.
/// </summary>
public sealed class AssistantSettings
{
    /// <summary>Whether LLM integration is enabled.</summary>
    public bool LlmEnabled { get; set; }

    /// <summary>Base URL for the OpenAI-compatible LLM endpoint.</summary>
    public string? LlmEndpoint { get; set; }

    /// <summary>API key for the LLM endpoint.</summary>
    public string? LlmApiKey { get; set; }

    /// <summary>Model identifier to use for completions.</summary>
    public string? LlmModel { get; set; } = "gpt-4";

    /// <summary>Anomaly detection sensitivity from 0.0 (lenient) to 1.0 (strict).</summary>
    public double AnomalySensitivity { get; set; } = 0.5;

    /// <summary>Whether natural-language to SQL translation is enabled.</summary>
    public bool NlToSqlEnabled { get; set; } = true;

    /// <summary>Whether proactive anomaly alerts are shown automatically.</summary>
    public bool ProactiveAlerts { get; set; } = true;
}

/// <summary>
/// Result of translating a natural-language question to SQL.
/// </summary>
public sealed class NlSqlResult
{
    /// <summary>The original question asked by the user.</summary>
    public required string OriginalQuestion { get; init; }

    /// <summary>The SQL statement generated from the question.</summary>
    public required string GeneratedSql { get; init; }

    /// <summary>Confidence score from 0.0 to 1.0.</summary>
    public double Confidence { get; init; }

    /// <summary>Whether the generated SQL was executed against the broker.</summary>
    public bool WasExecuted { get; init; }

    /// <summary>Error message if translation or execution failed.</summary>
    public string? Error { get; init; }

    /// <summary>How the SQL was generated: Pattern, LLM, or Fallback.</summary>
    public NlSqlSource Source { get; init; } = NlSqlSource.Pattern;
}

/// <summary>
/// Indicates how a natural-language query was translated to SQL.
/// </summary>
public enum NlSqlSource
{
    /// <summary>Translated via regex pattern matching.</summary>
    Pattern,

    /// <summary>Translated via LLM completion.</summary>
    Llm,

    /// <summary>Fallback partial match (low confidence).</summary>
    Fallback
}
