using System.Text;
using Kuestenlogik.Surgewave.Plugins.Marketplace;

namespace Kuestenlogik.Surgewave.Cli.Commands.Setup;

/// <summary>
/// Renders a <see cref="SetupAnswers"/> into the two shell scripts the
/// wizard ships as deliverables: <c>setup.sh</c> for Linux/macOS
/// operators and <c>setup.ps1</c> for Windows operators. Both run the
/// same <c>surgewave plugins install</c> commands in the same order
/// (storage first, then protocols, then schema handlers, then
/// connectors — a sensible install precedence so a protocol that
/// references a schema handler does not fail to load).
///
/// Outputs are checked into the operator's deployment repo, so the
/// generator is deterministic: same answers in → byte-identical
/// scripts out.
/// </summary>
public static class SetupScriptGenerator
{
    public static string RenderBash(SetupAnswers answers) => Render(answers, ShellFlavor.Bash);

    public static string RenderPowerShell(SetupAnswers answers) => Render(answers, ShellFlavor.PowerShell);

    private static string Render(SetupAnswers a, ShellFlavor flavor)
    {
        var sb = new StringBuilder();
        EmitHeader(sb, flavor);
        EmitFailFast(sb, flavor);
        EmitComment(sb, flavor, "Generated by `surgewave setup` — re-run the wizard to regenerate.");
        sb.AppendLine();

        EmitSection(sb, flavor, "Storage engine");
        if (a.StorageEngine is { } storage)
        {
            EmitInstall(sb, flavor, storage);
        }
        else
        {
            EmitComment(sb, flavor, "(none — staying on the built-in default)");
        }
        sb.AppendLine();

        EmitGroup(sb, flavor, "Protocols", a.Protocols);
        EmitGroup(sb, flavor, "Schema handlers", a.SchemaHandlers);
        EmitGroup(sb, flavor, "Connectors", a.Connectors);

        EmitComment(sb, flavor, "Restart the broker so the freshly installed plugins are picked up.");
        return sb.ToString();
    }

    private static void EmitGroup(StringBuilder sb, ShellFlavor flavor, string title, IReadOnlyList<PluginMarketplaceEntry> entries)
    {
        EmitSection(sb, flavor, title);
        if (entries.Count == 0)
        {
            EmitComment(sb, flavor, $"(no {title.ToLowerInvariant()} selected)");
        }
        else
        {
            foreach (var entry in entries) EmitInstall(sb, flavor, entry);
        }
        sb.AppendLine();
    }

    private static void EmitHeader(StringBuilder sb, ShellFlavor flavor)
    {
        if (flavor == ShellFlavor.Bash)
        {
            sb.AppendLine("#!/usr/bin/env bash");
        }
    }

    private static void EmitFailFast(StringBuilder sb, ShellFlavor flavor)
    {
        if (flavor == ShellFlavor.Bash)
        {
            sb.AppendLine("set -euo pipefail");
        }
        else
        {
            sb.AppendLine("$ErrorActionPreference = 'Stop'");
        }
    }

    private static void EmitComment(StringBuilder sb, ShellFlavor flavor, string text) =>
        sb.Append('#').Append(' ').AppendLine(text);

    private static void EmitSection(StringBuilder sb, ShellFlavor flavor, string title) =>
        sb.AppendLine($"# ── {title} ─────────────────────────────────────────────────");

    private static void EmitInstall(StringBuilder sb, ShellFlavor flavor, PluginMarketplaceEntry entry) =>
        sb.AppendLine($"surgewave plugins install {entry.PackageId} --version {entry.Version} --from-nuget");

    private enum ShellFlavor { Bash, PowerShell }
}
