using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Kuestenlogik.Surgewave.SourceGenerators;

/// <summary>
/// Incremental source generator that emits a typed <c>{Type}Codec</c> static
/// class (JSON serialize/deserialize plus typed producer/consumer extensions)
/// for every <c>record</c> or <c>class</c> annotated with
/// <c>[SurgewaveSchema]</c>. The attribute itself is emitted by the generator
/// — there is no extra runtime package to reference.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SurgewaveSchemaGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Kuestenlogik.Surgewave.SurgewaveSchemaAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Kuestenlogik.Surgewave
        {
            /// <summary>
            /// Marks a record/class so the Surgewave source generator emits a
            /// typed <c>{TypeName}Codec</c> static class with JSON serialize /
            /// deserialize plus producer / consumer extensions on
            /// <c>IProducer&lt;string,byte[]&gt;</c> and
            /// <c>IConsumer&lt;string,byte[]&gt;</c>.
            /// </summary>
            [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
            internal sealed class SurgewaveSchemaAttribute : System.Attribute
            {
                /// <summary>
                /// Optional default topic name. When set, the generated
                /// <c>ProduceAsync</c> / <c>ConsumeAsync</c> extensions expose
                /// an overload that defaults to this topic.
                /// </summary>
                public string? Topic { get; init; }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("SurgewaveSchemaAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var schemaTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => ToSchemaModel(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(schemaTypes, static (ctx, model) =>
        {
            var source = EmitCodec(model);
            ctx.AddSource($"{model.SanitizedName}Codec.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static SchemaModel? ToSchemaModel(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
        {
            return null;
        }

        string? topic = null;
        foreach (var attr in ctx.Attributes)
        {
            foreach (var named in attr.NamedArguments)
            {
                if (named.Key == "Topic" && named.Value.Value is string s)
                {
                    topic = s;
                }
            }
        }

        return new SchemaModel(
            Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
            TypeName: symbol.Name,
            IsRecord: symbol.IsRecord,
            Topic: topic);
    }

    private static string EmitCodec(SchemaModel m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        var hasNs = !string.IsNullOrEmpty(m.Namespace);
        if (hasNs)
        {
            sb.Append("namespace ").Append(m.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        var indent = hasNs ? "    " : string.Empty;
        var codecName = m.TypeName + "Codec";

        sb.Append(indent).Append("/// <summary>Generated JSON codec + producer/consumer helpers for <see cref=\"").Append(m.TypeName).AppendLine("\"/>.</summary>");
        sb.Append(indent).Append("internal static class ").AppendLine(codecName);
        sb.Append(indent).AppendLine("{");

        // Cached JsonSerializerOptions — same instance per process for ↑ throughput.
        sb.Append(indent).AppendLine("    private static readonly JsonSerializerOptions _options = new(JsonSerializerDefaults.Web);");
        sb.AppendLine();

        // Serialize
        sb.Append(indent).Append("    /// <summary>Serialize the value to a UTF-8 JSON byte array.</summary>");
        sb.AppendLine();
        sb.Append(indent).Append("    public static byte[] Serialize(").Append(m.TypeName).AppendLine(" value)");
        sb.Append(indent).AppendLine("        => JsonSerializer.SerializeToUtf8Bytes(value, _options);");
        sb.AppendLine();

        // Deserialize
        sb.Append(indent).Append("    /// <summary>Deserialize a UTF-8 JSON byte array.</summary>");
        sb.AppendLine();
        sb.Append(indent).Append("    public static ").Append(m.TypeName).AppendLine("? Deserialize(ReadOnlySpan<byte> utf8Json)");
        sb.Append(indent).Append("        => JsonSerializer.Deserialize<").Append(m.TypeName).AppendLine(">(utf8Json, _options);");
        sb.AppendLine();

        // Default topic (compile-time constant if present)
        if (!string.IsNullOrEmpty(m.Topic))
        {
            sb.Append(indent).Append("    /// <summary>Default topic from <c>[SurgewaveSchema(Topic = ...)]</c>.</summary>");
            sb.AppendLine();
            sb.Append(indent).Append("    public const string DefaultTopic = \"").Append(EscapeStringLiteral(m.Topic!)).AppendLine("\";");
            sb.AppendLine();
        }

        sb.Append(indent).AppendLine("}");

        // Extension methods on IProducer / IConsumer — only when the Surgewave
        // client abstractions are referenced. Wrapped in a runtime-typed
        // dispatch so the generator stays decoupled from the client package
        // at source-gen time. We emit `partial` extension methods over
        // open-generic IProducer<string, byte[]> / IConsumer<string, byte[]>.
        sb.AppendLine();
        sb.Append(indent).Append("/// <summary>Producer/consumer extensions for <see cref=\"").Append(m.TypeName).AppendLine("\"/>.</summary>");
        sb.Append(indent).Append("internal static class ").Append(m.TypeName).AppendLine("ProducerConsumerExtensions");
        sb.Append(indent).AppendLine("{");

        // ProduceAsync — only emitted when Topic is set (otherwise caller must pass a topic explicitly)
        if (!string.IsNullOrEmpty(m.Topic))
        {
            sb.Append(indent).Append("    /// <summary>Serialize and produce a <see cref=\"").Append(m.TypeName).Append("\"/> to the default topic <c>").Append(EscapeXmlText(m.Topic!)).AppendLine("</c>.</summary>");
            sb.Append(indent).Append("    public static global::System.Threading.Tasks.Task<global::Kuestenlogik.Surgewave.Client.Abstractions.ProduceResult> ProduceAsync(");
            sb.AppendLine();
            sb.Append(indent).AppendLine("        this global::Kuestenlogik.Surgewave.Client.Abstractions.IProducer<string, byte[]> producer,");
            sb.Append(indent).Append("        ").Append(m.TypeName).AppendLine(" value,");
            sb.Append(indent).AppendLine("        string? key = null,");
            sb.Append(indent).AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
            sb.Append(indent).Append("        => producer.ProduceAsync(").Append(codecName).Append(".DefaultTopic, key, ").Append(codecName).AppendLine(".Serialize(value), cancellationToken);");
            sb.AppendLine();
        }

        // ProduceAsync (explicit topic) — always emitted
        sb.Append(indent).Append("    /// <summary>Serialize and produce a <see cref=\"").Append(m.TypeName).AppendLine("\"/> to the given topic.</summary>");
        sb.Append(indent).Append("    public static global::System.Threading.Tasks.Task<global::Kuestenlogik.Surgewave.Client.Abstractions.ProduceResult> ProduceAsync(");
        sb.AppendLine();
        sb.Append(indent).AppendLine("        this global::Kuestenlogik.Surgewave.Client.Abstractions.IProducer<string, byte[]> producer,");
        sb.Append(indent).AppendLine("        string topic,");
        sb.Append(indent).Append("        ").Append(m.TypeName).AppendLine(" value,");
        sb.Append(indent).AppendLine("        string? key = null,");
        sb.Append(indent).AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append(indent).Append("        => producer.ProduceAsync(topic, key, ").Append(codecName).AppendLine(".Serialize(value), cancellationToken);");
        sb.AppendLine();

        // ConsumeAsync — deserializes a single record into the typed value
        sb.Append(indent).Append("    /// <summary>Consume one record and deserialize it as <see cref=\"").Append(m.TypeName).AppendLine("\"/>.</summary>");
        sb.Append(indent).Append("    public static async global::System.Threading.Tasks.Task<").Append(m.TypeName).AppendLine("?> ConsumeAsync(");
        sb.Append(indent).AppendLine("        this global::Kuestenlogik.Surgewave.Client.Abstractions.IConsumer<string, byte[]> consumer,");
        sb.Append(indent).AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var result = await consumer.ConsumeAsync(cancellationToken).ConfigureAwait(false);");
        sb.Append(indent).Append("        return result is null ? default : ").Append(codecName).AppendLine(".Deserialize(result.Value);");
        sb.Append(indent).AppendLine("    }");

        sb.Append(indent).AppendLine("}");

        if (hasNs)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string EscapeStringLiteral(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    private static string EscapeXmlText(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private readonly record struct SchemaModel(string? Namespace, string TypeName, bool IsRecord, string? Topic)
    {
        public string SanitizedName => TypeName;
    }
}
