<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Client\Kuestenlogik.Surgewave.Client.csproj" />
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Schema.Registry.Client\Kuestenlogik.Surgewave.Schema.Registry.Client.csproj" />
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Schema.Registry.Serdes.Avro\Kuestenlogik.Surgewave.Schema.Registry.Serdes.Avro.csproj" />
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Schema.Registry.Serdes.Protobuf\Kuestenlogik.Surgewave.Schema.Registry.Serdes.Protobuf.csproj" />
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Schema.Registry.Serdes.FlatBuffers\Kuestenlogik.Surgewave.Schema.Registry.Serdes.FlatBuffers.csproj" />
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Schema.Registry.Serdes.Json\Kuestenlogik.Surgewave.Schema.Registry.Serdes.Json.csproj" />
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Protocol.Kafka\Kuestenlogik.Surgewave.Protocol.Kafka.csproj" />
    <ProjectReference Include="..\..\src\Kuestenlogik.Surgewave.Testing\Kuestenlogik.Surgewave.Testing.csproj" />
  </ItemGroup>

</Project>
