<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\benchmarks\Kuestenlogik.Surgewave.Benchmarks.Comparison\Kuestenlogik.Surgewave.Benchmarks.Comparison.csproj" />
  </ItemGroup>

</Project>
